<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_READY TO EAT</name>
   <tag></tag>
   <elementGuidId>81a3f0ae-0ede-449c-9f56-48d4e3a27ac4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/div/div/div/aside/aside/ul/li[9]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.cat-item.cat-item-81 > a.site-secondary-font</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>86048fce-6c1e-48a8-97c9-94068231963e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>site-secondary-font</value>
      <webElementGuid>c2ac3f53-e1b8-418f-8dc3-6dfaf0021ed2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://kotakoki.wijaysali.my.id/product-category/ready-to-eat/</value>
      <webElementGuid>f25000be-8e13-46f3-9190-f2b37b2e880c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>READY TO EAT</value>
      <webElementGuid>44ba2cfc-9baf-4587-904c-e97dd8abeabb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;small-12 large-3 columns show-for-large&quot;]/div[@class=&quot;woocommerce-sidebar-sticky&quot;]/aside[@class=&quot;site-sidebar site-sidebar--shop widget-area&quot;]/aside[@class=&quot;widget woocommerce widget_product_categories_with_icon&quot;]/ul[@class=&quot;product-categories-with-icon&quot;]/li[@class=&quot;cat-item cat-item-81&quot;]/a[@class=&quot;site-secondary-font&quot;]</value>
      <webElementGuid>0091295e-a48e-4fe3-a420-3b07d3908d02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/div/div/aside/aside/ul/li[9]/a</value>
      <webElementGuid>a0865020-7475-4c17-ae27-ccf73cec9e17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'READY TO EAT')]</value>
      <webElementGuid>b2fe62dc-f4b5-407c-8384-d85c820253bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PIPILTIN COCOA'])[2]/following::a[1]</value>
      <webElementGuid>1be2a524-b093-423e-94cb-7a34b21b9849</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KOTAKOKI SET'])[2]/following::a[2]</value>
      <webElementGuid>aaae7c9c-a50e-4530-9160-7586620c0245</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SEAFOOD'])[2]/preceding::a[1]</value>
      <webElementGuid>7b5ca864-a699-47c5-a26a-504fbcb5bf2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SPICES'])[2]/preceding::a[2]</value>
      <webElementGuid>1e504fb9-f10d-4648-9a23-201b939bf64f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://kotakoki.wijaysali.my.id/product-category/ready-to-eat/')]</value>
      <webElementGuid>0f561384-92f8-4624-a628-d74cc9e3e2b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[9]/a</value>
      <webElementGuid>686a7107-b90e-41ea-b6d8-c781ce970b1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://kotakoki.wijaysali.my.id/product-category/ready-to-eat/' and (text() = 'READY TO EAT' or . = 'READY TO EAT')]</value>
      <webElementGuid>45ad4281-292c-4fdc-88d9-606c8e6e3b06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
