<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>nav_HomeUncategorizedAlbum</name>
   <tag></tag>
   <elementGuidId>e047f5ef-3e07-49aa-a883-8b0b00dd7d44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product-17']/div/div/div[2]/div/nav</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>nav.woocommerce-breadcrumb</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>nav</value>
      <webElementGuid>9366e005-087f-4c1a-be33-c00fad38c2f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>woocommerce-breadcrumb</value>
      <webElementGuid>b800d518-6edf-460a-94a4-f0a0d7bd4084</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Home/Uncategorized/Album</value>
      <webElementGuid>fe8fe46c-069b-44f1-a8c9-86451d730f6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-17&quot;)/div[@class=&quot;product_infos&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;small-12 large-5 columns&quot;]/div[@class=&quot;summary entry-summary&quot;]/nav[@class=&quot;woocommerce-breadcrumb&quot;]</value>
      <webElementGuid>322841b2-e7a6-4b79-be38-c437e22772a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-17']/div/div/div[2]/div/nav</value>
      <webElementGuid>56998cba-cae3-499d-b5b5-0347af3be203</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zoom'])[1]/following::nav[1]</value>
      <webElementGuid>ac75742a-c293-4489-a2b8-2f5b1ef4a3c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New!'])[1]/following::nav[1]</value>
      <webElementGuid>f3466769-1029-4e75-bc72-a8d3eb587952</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/nav</value>
      <webElementGuid>78a230e6-f407-4d0b-b177-7d7e05b60796</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//nav[(text() = 'Home/Uncategorized/Album' or . = 'Home/Uncategorized/Album')]</value>
      <webElementGuid>8ec86928-ac3e-4e17-b2cb-445c6f6fcd9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
