<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Filters_thehanger-icons-display-grid</name>
   <tag></tag>
   <elementGuidId>f40deede-41dd-4298-ada6-92e64ad40300</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/div/div[2]/div/div/header/div/div/div/span/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.thehanger-icons-display-grid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>40249a6b-3710-418e-9fae-8176c9981634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>thehanger-icons-display-grid</value>
      <webElementGuid>a81f756a-9238-443c-8f91-5d1a228895ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;small-12 large-9 columns&quot;]/div[@class=&quot;site-main-content-wrapper&quot;]/div[@class=&quot;shop_header_placeholder&quot;]/header[@class=&quot;woocommerce-archive-header&quot;]/div[@class=&quot;woocommerce-archive-header-inside&quot;]/div[@class=&quot;woocommerce-archive-header-tools site-secondary-font site-secondary-color&quot;]/div[@class=&quot;shop-tools&quot;]/span[@class=&quot;shop-display-grid active&quot;]/i[@class=&quot;thehanger-icons-display-grid&quot;]</value>
      <webElementGuid>7e6f87c7-0698-4757-a3bb-5c3d5c34c4bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/div[2]/div/div/header/div/div/div/span/i</value>
      <webElementGuid>a347de11-2fb9-4fde-9801-a02ca66370ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/i</value>
      <webElementGuid>da154bf2-5c65-499b-a30f-b273ef20b980</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
