<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Filters_thehanger-icons-display-list</name>
   <tag></tag>
   <elementGuidId>6dc59aa8-2265-47df-92ce-b391a3b72354</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/div/div[2]/div/div/header/div/div/div/span[2]/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.thehanger-icons-display-list</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>db90fcab-1de3-410b-8e65-c0b0ba86735e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>thehanger-icons-display-list</value>
      <webElementGuid>04720f4a-674b-4e53-991c-cc396b53b676</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;small-12 large-9 columns&quot;]/div[@class=&quot;site-main-content-wrapper&quot;]/div[@class=&quot;shop_header_placeholder&quot;]/header[@class=&quot;woocommerce-archive-header&quot;]/div[@class=&quot;woocommerce-archive-header-inside&quot;]/div[@class=&quot;woocommerce-archive-header-tools site-secondary-font site-secondary-color&quot;]/div[@class=&quot;shop-tools&quot;]/span[@class=&quot;shop-display-list&quot;]/i[@class=&quot;thehanger-icons-display-list&quot;]</value>
      <webElementGuid>396fb665-c848-44e0-919a-bca892e6e6f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/div[2]/div/div/header/div/div/div/span[2]/i</value>
      <webElementGuid>87a22bac-87e1-4460-a700-f3e70fe58dbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/i</value>
      <webElementGuid>b7800856-7f01-45fc-af5d-447af518e03e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
