<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>nav_HomeShop</name>
   <tag></tag>
   <elementGuidId>e2df2e96-97bc-46a4-a04a-63b112ae9322</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/nav</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>nav.woocommerce-breadcrumb</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>nav</value>
      <webElementGuid>5fc2f3b4-22b0-48f6-9cb6-15d671d2c7d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>woocommerce-breadcrumb</value>
      <webElementGuid>35c5f55a-cfea-40fb-b6a9-3d062090bdfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Home/Shop</value>
      <webElementGuid>4d43d225-0b1e-4376-9515-709cff387c27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/nav[@class=&quot;woocommerce-breadcrumb&quot;]</value>
      <webElementGuid>7275215f-d07b-4a97-9f50-4839df6be875</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/nav</value>
      <webElementGuid>9669e327-021a-45f0-9196-a68ee0deebb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/following::nav[1]</value>
      <webElementGuid>543ad9af-e0b1-4bcd-9c65-fb16efead362</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search for:'])[1]/following::nav[1]</value>
      <webElementGuid>3f04d97c-5d29-4701-87be-c84bc1b7b981</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/nav</value>
      <webElementGuid>52a85af0-8ef2-4a24-abe0-80fd6f6db88e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//nav[(text() = 'Home/Shop' or . = 'Home/Shop')]</value>
      <webElementGuid>12c16179-f241-499e-832d-1302c35ebadf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
