<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_prefix__cls-1,.prefix__cls-3fillnone_685b4f</name>
   <tag></tag>
   <elementGuidId>82612390-d49e-41d3-9d4b-7691e3a2b667</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='payment-methods']/div/div[2]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b71439d3-4afb-4300-9a9b-29b0ece21c5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-6 box-border appearance-none cursor-pointer focus:outline-none flex items-center justify-between text-sm sm:text-base border-t-0</value>
      <webElementGuid>589ad508-05f1-4909-960f-4bb17ead91b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>accordion</value>
      <webElementGuid>68be12d6-58fe-4ff2-be0f-e8ab346d9f4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>.prefix__cls-1,.prefix__cls-3{fill:none}.prefix__cls-3{stroke:var(--color-bg-primary)}E-wallet / QRIS</value>
      <webElementGuid>402e4d82-b068-4d44-a79a-13c1e68d4d13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment-methods&quot;)/div[@class=&quot;tab w-full overflow-hidden border border-b-0 border-gray-100 rounded&quot;]/div[@class=&quot;flex flex-col border-b border-gray-100&quot;]/button[@class=&quot;p-6 box-border appearance-none cursor-pointer focus:outline-none flex items-center justify-between text-sm sm:text-base border-t-0&quot;]</value>
      <webElementGuid>59e5fa09-4b19-44b1-962a-2be1b72cbd47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment-methods']/div/div[2]/button</value>
      <webElementGuid>40f3ebc9-e81e-4c80-9690-0a8c6bbe7c26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bank Lain'])[1]/following::button[1]</value>
      <webElementGuid>9127ab49-b078-45be-a9f0-484f8336f620</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IDR 45.000'])[1]/following::button[2]</value>
      <webElementGuid>4e6cf812-f800-47d9-85ed-17e6cefbb779</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='atau Pindai QR Code untuk membayar'])[1]/preceding::button[1]</value>
      <webElementGuid>8c55f872-3a84-4d3f-9157-942d828ef76e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menerima pembayaran melalui aplikasi di bawah ini'])[1]/preceding::button[1]</value>
      <webElementGuid>b8446f8e-2157-4ae0-b219-dac85c14b381</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>3b374517-7de4-431b-aa5d-f0bb89aa831b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '.prefix__cls-1,.prefix__cls-3{fill:none}.prefix__cls-3{stroke:var(--color-bg-primary)}E-wallet / QRIS' or . = '.prefix__cls-1,.prefix__cls-3{fill:none}.prefix__cls-3{stroke:var(--color-bg-primary)}E-wallet / QRIS')]</value>
      <webElementGuid>9c2ffe21-d7e4-48f2-ad90-db4094e5c98e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
