<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_IDLC_w-16 h-16 rounded-md</name>
   <tag></tag>
   <elementGuidId>d6a28eea-f5d3-4767-a79f-a8cfba1aee26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.w-16.h-16.rounded-md</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3e654dae-116c-4e3f-8c7f-f06e4a8f2652</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://xnd-companies.s3.amazonaws.com/prod/1596430317769_512.jpg</value>
      <webElementGuid>ccd0475e-11ba-470c-8502-64eee8a92836</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-16 h-16 rounded-md</value>
      <webElementGuid>83f88065-70a6-4915-b0b9-d98c26b8e069</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>merchant-logo</value>
      <webElementGuid>3f09fc8e-0074-4bed-aa38-19790c2489d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[2]/div[@class=&quot;flex min-h-screen&quot;]/div[@class=&quot;pt-8 mx-32 w-3/5&quot;]/div[@class=&quot;flex items-center mb-4&quot;]/div[@class=&quot;flex items-center&quot;]/img[@class=&quot;w-16 h-16 rounded-md&quot;]</value>
      <webElementGuid>bc72e50b-0fa4-4131-9daa-29f2cfdd2444</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/div/div/div/img</value>
      <webElementGuid>794b6c15-e9ae-4b71-8f2a-700835e12ca8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='merchant-logo']</value>
      <webElementGuid>ccae136b-a186-43ba-a22f-e9169f4d2db6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>3a6a0d82-1a97-49d8-b085-c2f4679b1251</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://xnd-companies.s3.amazonaws.com/prod/1596430317769_512.jpg' and @alt = 'merchant-logo']</value>
      <webElementGuid>ec3fd860-29aa-4cdb-945b-d65f037693ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
