<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Subtotal</name>
   <tag></tag>
   <elementGuidId>aae26969-a75a-431f-9505-9838130000f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div/div[2]/div[3]/table/tbody/tr/td</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>1a0ec579-0060-40c7-9c5a-7e649cae0ebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-semibold pr-4 </value>
      <webElementGuid>4eb1744c-068d-4273-8a9b-208d39997769</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Subtotal</value>
      <webElementGuid>9bee9fa3-9524-4442-9171-b347eef7a1a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[2]/div[@class=&quot;flex min-h-screen&quot;]/div[@class=&quot;pt-8 px-16 w-2/5 bg-gray-100 bg-opacity-50 divide-y divide-gray-200 divide-solid&quot;]/div[@class=&quot;text-sm md:text-base&quot;]/table[@class=&quot;h-full mr-0 ml-auto w-auto mt-4&quot;]/tbody[1]/tr[@class=&quot;text-right&quot;]/td[@class=&quot;font-semibold pr-4&quot;]</value>
      <webElementGuid>1bce5a4e-3fdb-4e18-9d7f-25d77fdc7f52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/div[2]/div[3]/table/tbody/tr/td</value>
      <webElementGuid>dbc0bc3d-d776-4c2e-a4c5-ae5164c3f89a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IDR 45.000'])[2]/following::td[1]</value>
      <webElementGuid>98784036-e321-4254-afd3-53342efe63bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IDR 15.000'])[1]/following::td[1]</value>
      <webElementGuid>b3cca08e-825a-4e68-a29c-9ac44792d744</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IDR 45.000'])[3]/preceding::td[1]</value>
      <webElementGuid>d3b88de2-9ab1-4fd2-b014-9cfb2b7ffee3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jumlah Total'])[1]/preceding::td[2]</value>
      <webElementGuid>ebfcd907-513d-41fd-8669-e9e60f4e686a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Subtotal']/parent::*</value>
      <webElementGuid>deed5998-49d9-4aeb-9ec6-c72f0a9d8b7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td</value>
      <webElementGuid>b6fa3b91-edc6-4d32-bd46-6e3e8380b411</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Subtotal' or . = 'Subtotal')]</value>
      <webElementGuid>6a4edf88-11de-4d1b-9d4d-9521a7d0f28a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
