<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_Subtotal</name>
   <tag></tag>
   <elementGuidId>9175e97b-5b8a-49a9-988a-a06f704500e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='order_review']/table/thead/tr/th[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>th.product-total</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>95e74d4e-57f2-4092-adde-c0031db476c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-total</value>
      <webElementGuid>f8d65e70-3113-48e4-a02e-00a51583fd73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Subtotal</value>
      <webElementGuid>d12a4036-6436-4c54-a55b-8ef479a5a407</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;order_review&quot;)/table[@class=&quot;shop_table woocommerce-checkout-review-order-table&quot;]/thead[1]/tr[1]/th[@class=&quot;product-total&quot;]</value>
      <webElementGuid>43ab1a15-86c2-480c-9d35-1f8a98b910ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='order_review']/table/thead/tr/th[2]</value>
      <webElementGuid>ddd1250b-588c-4137-a296-084c6c2e00a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product'])[1]/following::th[1]</value>
      <webElementGuid>7cf3c1e7-d816-4f99-b644-c0b2bf7af011</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your order'])[1]/following::th[2]</value>
      <webElementGuid>e34cf039-703c-41f3-94d9-80a0614305b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='× 3'])[1]/preceding::th[1]</value>
      <webElementGuid>b8eb5e4f-0d26-4032-9958-7d211bbf2ff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Subtotal']/parent::*</value>
      <webElementGuid>ebd005d5-5074-4fe4-99b7-c26a1b0f48da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[2]</value>
      <webElementGuid>2ea14a9e-207a-4335-b11f-000feab2e074</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = 'Subtotal' or . = 'Subtotal')]</value>
      <webElementGuid>a40b91cc-0cec-4337-a3e3-8282a19a495a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
