<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_SHOP NOW_swiper-pagination-bullet</name>
   <tag></tag>
   <elementGuidId>0bf005ea-5816-49cf-b5f3-2ef4a3350277</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-152']/div/div/div/div/div/div/div[2]/span[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cd27601a-80f0-41a4-b939-10ecc167062f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>swiper-pagination-bullet</value>
      <webElementGuid>011cda8d-a9a7-4cce-85cd-18db3fd76e5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4a53f71c-c731-4c3d-a7cd-c91f993be79e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2937335a-a780-472a-ae57-ceafff0dd9fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Go to slide 3</value>
      <webElementGuid>fc084a58-ba84-4de3-a58b-4ad02c3f24cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-152&quot;)/div[@class=&quot;entry-content&quot;]/div[@class=&quot;vc_row wpb_row vc_row-fluid wpb_animate_when_almost_visible wpb_fadeIn fadeIn vc_custom_1653656722181 vc_row-no-padding wpb_start_animation animated&quot;]/div[@class=&quot;wpb_column vc_column_container vc_col-sm-12&quot;]/div[@class=&quot;vc_column-inner&quot;]/div[@class=&quot;wpb_wrapper&quot;]/div[@class=&quot;shortcode_getbowtied_slider swiper-container swiper-62cb64416a4f9 swiper-container-initialized swiper-container-horizontal&quot;]/div[@class=&quot;quickview-pagination shortcode-slider-pagination swiper-pagination-clickable swiper-pagination-bullets&quot;]/span[@class=&quot;swiper-pagination-bullet&quot;]</value>
      <webElementGuid>a7e60f87-0eaf-4ff2-adff-f042dfc81430</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-152']/div/div/div/div/div/div/div[2]/span[3]</value>
      <webElementGuid>366a1f85-1568-44f8-8b89-9d87570edf43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]</value>
      <webElementGuid>a217cbc3-e4ea-4629-ab55-82abda784490</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
